#!/bin/bash

# Script is generated by Gemini
#
# - mingyang
# Stop script on any error
set -e

# Trap errors for a clear exit message
trap 'echo "Error detected on line $LINENO. Deployment stopped."; exit 1' ERR

echo "Starting deployment process..."

# Check if directories exist
if [ ! -d "mrbs-ui" ] || [ ! -d "mrbs-backend" ]; then
    echo "Error: Could not find 'mrbs-ui' or 'mrbs-backend' directories."
    echo "Make sure you are running this script from the project root."
    exit 1
fi

# ---------------------------------------------------------
# STEP 1: Build Frontend
# ---------------------------------------------------------
echo "Entering frontend directory..."
cd mrbs-ui

echo "Installing dependencies..."
pnpm install --silent

echo "Building frontend..."
pnpm build

# ---------------------------------------------------------
# STEP 2: Move Artifacts
# ---------------------------------------------------------
BACKEND_DIR="../mrbs-backend"

echo "Cleaning old assets in backend..."
rm -rf "$BACKEND_DIR/dist"

echo "Moving new build to backend..."
mv dist "$BACKEND_DIR/"

# ---------------------------------------------------------
# STEP 3: Deploy
# ---------------------------------------------------------
echo "Entering backend directory..."
cd "$BACKEND_DIR"

echo "Deploying to Fly.io..."
fly deploy

echo "Deployment completed successfully."
