# Frontend IDE 
title rep-mrbs frontend nvim  
cd mrbs-ui 
launch nvim .

# Backend IDE 
new_os_window
title rep-mrbs backend nvim
cd mrbs-backend
launch nvim .

# Backend service 
new_os_window
title rep-mrbs backend terminal 
cd mrbs-backend 
launch zsh -c "go run main.go"

# ngrok tunnel 
new_os_window
title rep-mrbs terminal 
launch zsh -c "ngrok http 8080"
