/**
 *
 *  Areas.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Areas.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::postgres::mrbs;

const std::string Areas::Cols::_area_id = "\"area_id\"";
const std::string Areas::Cols::_resolution = "\"resolution\"";
const std::string Areas::Cols::_default_duration = "\"default_duration\"";
const std::string Areas::Cols::_display_name = "\"display_name\"";
const std::string Areas::Cols::_morning_starts = "\"morning_starts\"";
const std::string Areas::Cols::_evening_ends = "\"evening_ends\"";
const std::string Areas::Cols::_max_per_day = "\"max_per_day\"";
const std::string Areas::Cols::_max_per_week = "\"max_per_week\"";
const std::string Areas::Cols::_max_duration = "\"max_duration\"";
const std::string Areas::primaryKeyName = "area_id";
const bool Areas::hasPrimaryKey = true;
const std::string Areas::tableName = "mrbs.\"areas\"";

const std::vector<typename Areas::MetaData> Areas::metaData_={
{"area_id","int32_t","integer",4,1,1,1},
{"resolution","std::string","interval",0,0,0,1},
{"default_duration","std::string","interval",0,0,0,1},
{"display_name","std::string","text",0,0,0,0},
{"morning_starts","std::string","time without time zone",0,0,0,1},
{"evening_ends","std::string","time without time zone",0,0,0,1},
{"max_per_day","int32_t","integer",4,0,0,0},
{"max_per_week","int32_t","integer",4,0,0,0},
{"max_duration","std::string","interval",0,0,0,0}
};
const std::string &Areas::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Areas::Areas(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["area_id"].isNull())
        {
            areaId_=std::make_shared<int32_t>(r["area_id"].as<int32_t>());
        }
        if(!r["resolution"].isNull())
        {
            resolution_=std::make_shared<std::string>(r["resolution"].as<std::string>());
        }
        if(!r["default_duration"].isNull())
        {
            defaultDuration_=std::make_shared<std::string>(r["default_duration"].as<std::string>());
        }
        if(!r["display_name"].isNull())
        {
            displayName_=std::make_shared<std::string>(r["display_name"].as<std::string>());
        }
        if(!r["morning_starts"].isNull())
        {
            morningStarts_=std::make_shared<std::string>(r["morning_starts"].as<std::string>());
        }
        if(!r["evening_ends"].isNull())
        {
            eveningEnds_=std::make_shared<std::string>(r["evening_ends"].as<std::string>());
        }
        if(!r["max_per_day"].isNull())
        {
            maxPerDay_=std::make_shared<int32_t>(r["max_per_day"].as<int32_t>());
        }
        if(!r["max_per_week"].isNull())
        {
            maxPerWeek_=std::make_shared<int32_t>(r["max_per_week"].as<int32_t>());
        }
        if(!r["max_duration"].isNull())
        {
            maxDuration_=std::make_shared<std::string>(r["max_duration"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 9 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            areaId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            resolution_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            defaultDuration_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            displayName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            morningStarts_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            eveningEnds_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            maxPerDay_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            maxPerWeek_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            maxDuration_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Areas::Areas(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            areaId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            resolution_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            defaultDuration_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            displayName_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            morningStarts_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            eveningEnds_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            maxPerDay_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            maxPerWeek_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            maxDuration_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
}

Areas::Areas(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("area_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["area_id"].isNull())
        {
            areaId_=std::make_shared<int32_t>((int32_t)pJson["area_id"].asInt64());
        }
    }
    if(pJson.isMember("resolution"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["resolution"].isNull())
        {
            resolution_=std::make_shared<std::string>(pJson["resolution"].asString());
        }
    }
    if(pJson.isMember("default_duration"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["default_duration"].isNull())
        {
            defaultDuration_=std::make_shared<std::string>(pJson["default_duration"].asString());
        }
    }
    if(pJson.isMember("display_name"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["display_name"].isNull())
        {
            displayName_=std::make_shared<std::string>(pJson["display_name"].asString());
        }
    }
    if(pJson.isMember("morning_starts"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["morning_starts"].isNull())
        {
            morningStarts_=std::make_shared<std::string>(pJson["morning_starts"].asString());
        }
    }
    if(pJson.isMember("evening_ends"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["evening_ends"].isNull())
        {
            eveningEnds_=std::make_shared<std::string>(pJson["evening_ends"].asString());
        }
    }
    if(pJson.isMember("max_per_day"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["max_per_day"].isNull())
        {
            maxPerDay_=std::make_shared<int32_t>((int32_t)pJson["max_per_day"].asInt64());
        }
    }
    if(pJson.isMember("max_per_week"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["max_per_week"].isNull())
        {
            maxPerWeek_=std::make_shared<int32_t>((int32_t)pJson["max_per_week"].asInt64());
        }
    }
    if(pJson.isMember("max_duration"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["max_duration"].isNull())
        {
            maxDuration_=std::make_shared<std::string>(pJson["max_duration"].asString());
        }
    }
}

void Areas::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            areaId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            resolution_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            defaultDuration_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            displayName_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            morningStarts_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            eveningEnds_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            maxPerDay_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            maxPerWeek_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            maxDuration_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
}

void Areas::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("area_id"))
    {
        if(!pJson["area_id"].isNull())
        {
            areaId_=std::make_shared<int32_t>((int32_t)pJson["area_id"].asInt64());
        }
    }
    if(pJson.isMember("resolution"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["resolution"].isNull())
        {
            resolution_=std::make_shared<std::string>(pJson["resolution"].asString());
        }
    }
    if(pJson.isMember("default_duration"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["default_duration"].isNull())
        {
            defaultDuration_=std::make_shared<std::string>(pJson["default_duration"].asString());
        }
    }
    if(pJson.isMember("display_name"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["display_name"].isNull())
        {
            displayName_=std::make_shared<std::string>(pJson["display_name"].asString());
        }
    }
    if(pJson.isMember("morning_starts"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["morning_starts"].isNull())
        {
            morningStarts_=std::make_shared<std::string>(pJson["morning_starts"].asString());
        }
    }
    if(pJson.isMember("evening_ends"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["evening_ends"].isNull())
        {
            eveningEnds_=std::make_shared<std::string>(pJson["evening_ends"].asString());
        }
    }
    if(pJson.isMember("max_per_day"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["max_per_day"].isNull())
        {
            maxPerDay_=std::make_shared<int32_t>((int32_t)pJson["max_per_day"].asInt64());
        }
    }
    if(pJson.isMember("max_per_week"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["max_per_week"].isNull())
        {
            maxPerWeek_=std::make_shared<int32_t>((int32_t)pJson["max_per_week"].asInt64());
        }
    }
    if(pJson.isMember("max_duration"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["max_duration"].isNull())
        {
            maxDuration_=std::make_shared<std::string>(pJson["max_duration"].asString());
        }
    }
}

const int32_t &Areas::getValueOfAreaId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(areaId_)
        return *areaId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Areas::getAreaId() const noexcept
{
    return areaId_;
}
void Areas::setAreaId(const int32_t &pAreaId) noexcept
{
    areaId_ = std::make_shared<int32_t>(pAreaId);
    dirtyFlag_[0] = true;
}
const typename Areas::PrimaryKeyType & Areas::getPrimaryKey() const
{
    assert(areaId_);
    return *areaId_;
}

const std::string &Areas::getValueOfResolution() const noexcept
{
    static const std::string defaultValue = std::string();
    if(resolution_)
        return *resolution_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Areas::getResolution() const noexcept
{
    return resolution_;
}
void Areas::setResolution(const std::string &pResolution) noexcept
{
    resolution_ = std::make_shared<std::string>(pResolution);
    dirtyFlag_[1] = true;
}
void Areas::setResolution(std::string &&pResolution) noexcept
{
    resolution_ = std::make_shared<std::string>(std::move(pResolution));
    dirtyFlag_[1] = true;
}

const std::string &Areas::getValueOfDefaultDuration() const noexcept
{
    static const std::string defaultValue = std::string();
    if(defaultDuration_)
        return *defaultDuration_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Areas::getDefaultDuration() const noexcept
{
    return defaultDuration_;
}
void Areas::setDefaultDuration(const std::string &pDefaultDuration) noexcept
{
    defaultDuration_ = std::make_shared<std::string>(pDefaultDuration);
    dirtyFlag_[2] = true;
}
void Areas::setDefaultDuration(std::string &&pDefaultDuration) noexcept
{
    defaultDuration_ = std::make_shared<std::string>(std::move(pDefaultDuration));
    dirtyFlag_[2] = true;
}

const std::string &Areas::getValueOfDisplayName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(displayName_)
        return *displayName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Areas::getDisplayName() const noexcept
{
    return displayName_;
}
void Areas::setDisplayName(const std::string &pDisplayName) noexcept
{
    displayName_ = std::make_shared<std::string>(pDisplayName);
    dirtyFlag_[3] = true;
}
void Areas::setDisplayName(std::string &&pDisplayName) noexcept
{
    displayName_ = std::make_shared<std::string>(std::move(pDisplayName));
    dirtyFlag_[3] = true;
}
void Areas::setDisplayNameToNull() noexcept
{
    displayName_.reset();
    dirtyFlag_[3] = true;
}

const std::string &Areas::getValueOfMorningStarts() const noexcept
{
    static const std::string defaultValue = std::string();
    if(morningStarts_)
        return *morningStarts_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Areas::getMorningStarts() const noexcept
{
    return morningStarts_;
}
void Areas::setMorningStarts(const std::string &pMorningStarts) noexcept
{
    morningStarts_ = std::make_shared<std::string>(pMorningStarts);
    dirtyFlag_[4] = true;
}
void Areas::setMorningStarts(std::string &&pMorningStarts) noexcept
{
    morningStarts_ = std::make_shared<std::string>(std::move(pMorningStarts));
    dirtyFlag_[4] = true;
}

const std::string &Areas::getValueOfEveningEnds() const noexcept
{
    static const std::string defaultValue = std::string();
    if(eveningEnds_)
        return *eveningEnds_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Areas::getEveningEnds() const noexcept
{
    return eveningEnds_;
}
void Areas::setEveningEnds(const std::string &pEveningEnds) noexcept
{
    eveningEnds_ = std::make_shared<std::string>(pEveningEnds);
    dirtyFlag_[5] = true;
}
void Areas::setEveningEnds(std::string &&pEveningEnds) noexcept
{
    eveningEnds_ = std::make_shared<std::string>(std::move(pEveningEnds));
    dirtyFlag_[5] = true;
}

const int32_t &Areas::getValueOfMaxPerDay() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(maxPerDay_)
        return *maxPerDay_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Areas::getMaxPerDay() const noexcept
{
    return maxPerDay_;
}
void Areas::setMaxPerDay(const int32_t &pMaxPerDay) noexcept
{
    maxPerDay_ = std::make_shared<int32_t>(pMaxPerDay);
    dirtyFlag_[6] = true;
}
void Areas::setMaxPerDayToNull() noexcept
{
    maxPerDay_.reset();
    dirtyFlag_[6] = true;
}

const int32_t &Areas::getValueOfMaxPerWeek() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(maxPerWeek_)
        return *maxPerWeek_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Areas::getMaxPerWeek() const noexcept
{
    return maxPerWeek_;
}
void Areas::setMaxPerWeek(const int32_t &pMaxPerWeek) noexcept
{
    maxPerWeek_ = std::make_shared<int32_t>(pMaxPerWeek);
    dirtyFlag_[7] = true;
}
void Areas::setMaxPerWeekToNull() noexcept
{
    maxPerWeek_.reset();
    dirtyFlag_[7] = true;
}

const std::string &Areas::getValueOfMaxDuration() const noexcept
{
    static const std::string defaultValue = std::string();
    if(maxDuration_)
        return *maxDuration_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Areas::getMaxDuration() const noexcept
{
    return maxDuration_;
}
void Areas::setMaxDuration(const std::string &pMaxDuration) noexcept
{
    maxDuration_ = std::make_shared<std::string>(pMaxDuration);
    dirtyFlag_[8] = true;
}
void Areas::setMaxDuration(std::string &&pMaxDuration) noexcept
{
    maxDuration_ = std::make_shared<std::string>(std::move(pMaxDuration));
    dirtyFlag_[8] = true;
}
void Areas::setMaxDurationToNull() noexcept
{
    maxDuration_.reset();
    dirtyFlag_[8] = true;
}

void Areas::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Areas::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "resolution",
        "default_duration",
        "display_name",
        "morning_starts",
        "evening_ends",
        "max_per_day",
        "max_per_week",
        "max_duration"
    };
    return inCols;
}

void Areas::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getResolution())
        {
            binder << getValueOfResolution();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDefaultDuration())
        {
            binder << getValueOfDefaultDuration();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDisplayName())
        {
            binder << getValueOfDisplayName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getMorningStarts())
        {
            binder << getValueOfMorningStarts();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEveningEnds())
        {
            binder << getValueOfEveningEnds();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMaxPerDay())
        {
            binder << getValueOfMaxPerDay();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getMaxPerWeek())
        {
            binder << getValueOfMaxPerWeek();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getMaxDuration())
        {
            binder << getValueOfMaxDuration();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Areas::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    return ret;
}

void Areas::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getResolution())
        {
            binder << getValueOfResolution();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDefaultDuration())
        {
            binder << getValueOfDefaultDuration();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDisplayName())
        {
            binder << getValueOfDisplayName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getMorningStarts())
        {
            binder << getValueOfMorningStarts();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEveningEnds())
        {
            binder << getValueOfEveningEnds();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMaxPerDay())
        {
            binder << getValueOfMaxPerDay();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getMaxPerWeek())
        {
            binder << getValueOfMaxPerWeek();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getMaxDuration())
        {
            binder << getValueOfMaxDuration();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Areas::toJson() const
{
    Json::Value ret;
    if(getAreaId())
    {
        ret["area_id"]=getValueOfAreaId();
    }
    else
    {
        ret["area_id"]=Json::Value();
    }
    if(getResolution())
    {
        ret["resolution"]=getValueOfResolution();
    }
    else
    {
        ret["resolution"]=Json::Value();
    }
    if(getDefaultDuration())
    {
        ret["default_duration"]=getValueOfDefaultDuration();
    }
    else
    {
        ret["default_duration"]=Json::Value();
    }
    if(getDisplayName())
    {
        ret["display_name"]=getValueOfDisplayName();
    }
    else
    {
        ret["display_name"]=Json::Value();
    }
    if(getMorningStarts())
    {
        ret["morning_starts"]=getValueOfMorningStarts();
    }
    else
    {
        ret["morning_starts"]=Json::Value();
    }
    if(getEveningEnds())
    {
        ret["evening_ends"]=getValueOfEveningEnds();
    }
    else
    {
        ret["evening_ends"]=Json::Value();
    }
    if(getMaxPerDay())
    {
        ret["max_per_day"]=getValueOfMaxPerDay();
    }
    else
    {
        ret["max_per_day"]=Json::Value();
    }
    if(getMaxPerWeek())
    {
        ret["max_per_week"]=getValueOfMaxPerWeek();
    }
    else
    {
        ret["max_per_week"]=Json::Value();
    }
    if(getMaxDuration())
    {
        ret["max_duration"]=getValueOfMaxDuration();
    }
    else
    {
        ret["max_duration"]=Json::Value();
    }
    return ret;
}

Json::Value Areas::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 9)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getAreaId())
            {
                ret[pMasqueradingVector[0]]=getValueOfAreaId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getResolution())
            {
                ret[pMasqueradingVector[1]]=getValueOfResolution();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDefaultDuration())
            {
                ret[pMasqueradingVector[2]]=getValueOfDefaultDuration();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDisplayName())
            {
                ret[pMasqueradingVector[3]]=getValueOfDisplayName();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getMorningStarts())
            {
                ret[pMasqueradingVector[4]]=getValueOfMorningStarts();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getEveningEnds())
            {
                ret[pMasqueradingVector[5]]=getValueOfEveningEnds();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getMaxPerDay())
            {
                ret[pMasqueradingVector[6]]=getValueOfMaxPerDay();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getMaxPerWeek())
            {
                ret[pMasqueradingVector[7]]=getValueOfMaxPerWeek();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getMaxDuration())
            {
                ret[pMasqueradingVector[8]]=getValueOfMaxDuration();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getAreaId())
    {
        ret["area_id"]=getValueOfAreaId();
    }
    else
    {
        ret["area_id"]=Json::Value();
    }
    if(getResolution())
    {
        ret["resolution"]=getValueOfResolution();
    }
    else
    {
        ret["resolution"]=Json::Value();
    }
    if(getDefaultDuration())
    {
        ret["default_duration"]=getValueOfDefaultDuration();
    }
    else
    {
        ret["default_duration"]=Json::Value();
    }
    if(getDisplayName())
    {
        ret["display_name"]=getValueOfDisplayName();
    }
    else
    {
        ret["display_name"]=Json::Value();
    }
    if(getMorningStarts())
    {
        ret["morning_starts"]=getValueOfMorningStarts();
    }
    else
    {
        ret["morning_starts"]=Json::Value();
    }
    if(getEveningEnds())
    {
        ret["evening_ends"]=getValueOfEveningEnds();
    }
    else
    {
        ret["evening_ends"]=Json::Value();
    }
    if(getMaxPerDay())
    {
        ret["max_per_day"]=getValueOfMaxPerDay();
    }
    else
    {
        ret["max_per_day"]=Json::Value();
    }
    if(getMaxPerWeek())
    {
        ret["max_per_week"]=getValueOfMaxPerWeek();
    }
    else
    {
        ret["max_per_week"]=Json::Value();
    }
    if(getMaxDuration())
    {
        ret["max_duration"]=getValueOfMaxDuration();
    }
    else
    {
        ret["max_duration"]=Json::Value();
    }
    return ret;
}

bool Areas::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("area_id"))
    {
        if(!validJsonOfField(0, "area_id", pJson["area_id"], err, true))
            return false;
    }
    if(pJson.isMember("resolution"))
    {
        if(!validJsonOfField(1, "resolution", pJson["resolution"], err, true))
            return false;
    }
    if(pJson.isMember("default_duration"))
    {
        if(!validJsonOfField(2, "default_duration", pJson["default_duration"], err, true))
            return false;
    }
    if(pJson.isMember("display_name"))
    {
        if(!validJsonOfField(3, "display_name", pJson["display_name"], err, true))
            return false;
    }
    if(pJson.isMember("morning_starts"))
    {
        if(!validJsonOfField(4, "morning_starts", pJson["morning_starts"], err, true))
            return false;
    }
    else
    {
        err="The morning_starts column cannot be null";
        return false;
    }
    if(pJson.isMember("evening_ends"))
    {
        if(!validJsonOfField(5, "evening_ends", pJson["evening_ends"], err, true))
            return false;
    }
    else
    {
        err="The evening_ends column cannot be null";
        return false;
    }
    if(pJson.isMember("max_per_day"))
    {
        if(!validJsonOfField(6, "max_per_day", pJson["max_per_day"], err, true))
            return false;
    }
    if(pJson.isMember("max_per_week"))
    {
        if(!validJsonOfField(7, "max_per_week", pJson["max_per_week"], err, true))
            return false;
    }
    if(pJson.isMember("max_duration"))
    {
        if(!validJsonOfField(8, "max_duration", pJson["max_duration"], err, true))
            return false;
    }
    return true;
}
bool Areas::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Areas::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("area_id"))
    {
        if(!validJsonOfField(0, "area_id", pJson["area_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("resolution"))
    {
        if(!validJsonOfField(1, "resolution", pJson["resolution"], err, false))
            return false;
    }
    if(pJson.isMember("default_duration"))
    {
        if(!validJsonOfField(2, "default_duration", pJson["default_duration"], err, false))
            return false;
    }
    if(pJson.isMember("display_name"))
    {
        if(!validJsonOfField(3, "display_name", pJson["display_name"], err, false))
            return false;
    }
    if(pJson.isMember("morning_starts"))
    {
        if(!validJsonOfField(4, "morning_starts", pJson["morning_starts"], err, false))
            return false;
    }
    if(pJson.isMember("evening_ends"))
    {
        if(!validJsonOfField(5, "evening_ends", pJson["evening_ends"], err, false))
            return false;
    }
    if(pJson.isMember("max_per_day"))
    {
        if(!validJsonOfField(6, "max_per_day", pJson["max_per_day"], err, false))
            return false;
    }
    if(pJson.isMember("max_per_week"))
    {
        if(!validJsonOfField(7, "max_per_week", pJson["max_per_week"], err, false))
            return false;
    }
    if(pJson.isMember("max_duration"))
    {
        if(!validJsonOfField(8, "max_duration", pJson["max_duration"], err, false))
            return false;
    }
    return true;
}
bool Areas::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Areas::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
