/**
 *
 *  Areas.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace postgres
{
namespace mrbs
{

class Areas
{
  public:
    struct Cols
    {
        static const std::string _area_id;
        static const std::string _resolution;
        static const std::string _default_duration;
        static const std::string _display_name;
        static const std::string _morning_starts;
        static const std::string _evening_ends;
        static const std::string _max_per_day;
        static const std::string _max_per_week;
        static const std::string _max_duration;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Areas(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Areas(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Areas(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Areas() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column area_id  */
    ///Get the value of the column area_id, returns the default value if the column is null
    const int32_t &getValueOfAreaId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getAreaId() const noexcept;
    ///Set the value of the column area_id
    void setAreaId(const int32_t &pAreaId) noexcept;

    /**  For column resolution  */
    ///Get the value of the column resolution, returns the default value if the column is null
    const std::string &getValueOfResolution() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getResolution() const noexcept;
    ///Set the value of the column resolution
    void setResolution(const std::string &pResolution) noexcept;
    void setResolution(std::string &&pResolution) noexcept;

    /**  For column default_duration  */
    ///Get the value of the column default_duration, returns the default value if the column is null
    const std::string &getValueOfDefaultDuration() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDefaultDuration() const noexcept;
    ///Set the value of the column default_duration
    void setDefaultDuration(const std::string &pDefaultDuration) noexcept;
    void setDefaultDuration(std::string &&pDefaultDuration) noexcept;

    /**  For column display_name  */
    ///Get the value of the column display_name, returns the default value if the column is null
    const std::string &getValueOfDisplayName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDisplayName() const noexcept;
    ///Set the value of the column display_name
    void setDisplayName(const std::string &pDisplayName) noexcept;
    void setDisplayName(std::string &&pDisplayName) noexcept;
    void setDisplayNameToNull() noexcept;

    /**  For column morning_starts  */
    ///Get the value of the column morning_starts, returns the default value if the column is null
    const std::string &getValueOfMorningStarts() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMorningStarts() const noexcept;
    ///Set the value of the column morning_starts
    void setMorningStarts(const std::string &pMorningStarts) noexcept;
    void setMorningStarts(std::string &&pMorningStarts) noexcept;

    /**  For column evening_ends  */
    ///Get the value of the column evening_ends, returns the default value if the column is null
    const std::string &getValueOfEveningEnds() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEveningEnds() const noexcept;
    ///Set the value of the column evening_ends
    void setEveningEnds(const std::string &pEveningEnds) noexcept;
    void setEveningEnds(std::string &&pEveningEnds) noexcept;

    /**  For column max_per_day  */
    ///Get the value of the column max_per_day, returns the default value if the column is null
    const int32_t &getValueOfMaxPerDay() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getMaxPerDay() const noexcept;
    ///Set the value of the column max_per_day
    void setMaxPerDay(const int32_t &pMaxPerDay) noexcept;
    void setMaxPerDayToNull() noexcept;

    /**  For column max_per_week  */
    ///Get the value of the column max_per_week, returns the default value if the column is null
    const int32_t &getValueOfMaxPerWeek() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getMaxPerWeek() const noexcept;
    ///Set the value of the column max_per_week
    void setMaxPerWeek(const int32_t &pMaxPerWeek) noexcept;
    void setMaxPerWeekToNull() noexcept;

    /**  For column max_duration  */
    ///Get the value of the column max_duration, returns the default value if the column is null
    const std::string &getValueOfMaxDuration() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMaxDuration() const noexcept;
    ///Set the value of the column max_duration
    void setMaxDuration(const std::string &pMaxDuration) noexcept;
    void setMaxDuration(std::string &&pMaxDuration) noexcept;
    void setMaxDurationToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 9;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Areas>;
    friend drogon::orm::BaseBuilder<Areas, true, true>;
    friend drogon::orm::BaseBuilder<Areas, true, false>;
    friend drogon::orm::BaseBuilder<Areas, false, true>;
    friend drogon::orm::BaseBuilder<Areas, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Areas>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> areaId_;
    std::shared_ptr<std::string> resolution_;
    std::shared_ptr<std::string> defaultDuration_;
    std::shared_ptr<std::string> displayName_;
    std::shared_ptr<std::string> morningStarts_;
    std::shared_ptr<std::string> eveningEnds_;
    std::shared_ptr<int32_t> maxPerDay_;
    std::shared_ptr<int32_t> maxPerWeek_;
    std::shared_ptr<std::string> maxDuration_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[9]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where area_id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where area_id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "area_id,";
            ++parametersCount;
        sql += "resolution,";
        ++parametersCount;
        if(!dirtyFlag_[1])
        {
            needSelection=true;
        }
        sql += "default_duration,";
        ++parametersCount;
        if(!dirtyFlag_[2])
        {
            needSelection=true;
        }
        if(dirtyFlag_[3])
        {
            sql += "display_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "morning_starts,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "evening_ends,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "max_per_day,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "max_per_week,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "max_duration,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace mrbs
} // namespace postgres
} // namespace drogon_model
