/**
 *
 *  Rooms.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace postgres
{
namespace mrbs
{

class Rooms
{
  public:
    struct Cols
    {
        static const std::string _room_id;
        static const std::string _area_id;
        static const std::string _display_name;
        static const std::string _sort_key;
        static const std::string _description;
        static const std::string _capacity;
        static const std::string _admin_email;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Rooms(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Rooms(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Rooms(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Rooms() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column room_id  */
    ///Get the value of the column room_id, returns the default value if the column is null
    const int32_t &getValueOfRoomId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getRoomId() const noexcept;
    ///Set the value of the column room_id
    void setRoomId(const int32_t &pRoomId) noexcept;

    /**  For column area_id  */
    ///Get the value of the column area_id, returns the default value if the column is null
    const int32_t &getValueOfAreaId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getAreaId() const noexcept;
    ///Set the value of the column area_id
    void setAreaId(const int32_t &pAreaId) noexcept;

    /**  For column display_name  */
    ///Get the value of the column display_name, returns the default value if the column is null
    const std::string &getValueOfDisplayName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDisplayName() const noexcept;
    ///Set the value of the column display_name
    void setDisplayName(const std::string &pDisplayName) noexcept;
    void setDisplayName(std::string &&pDisplayName) noexcept;

    /**  For column sort_key  */
    ///Get the value of the column sort_key, returns the default value if the column is null
    const std::string &getValueOfSortKey() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSortKey() const noexcept;
    ///Set the value of the column sort_key
    void setSortKey(const std::string &pSortKey) noexcept;
    void setSortKey(std::string &&pSortKey) noexcept;

    /**  For column description  */
    ///Get the value of the column description, returns the default value if the column is null
    const std::string &getValueOfDescription() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDescription() const noexcept;
    ///Set the value of the column description
    void setDescription(const std::string &pDescription) noexcept;
    void setDescription(std::string &&pDescription) noexcept;
    void setDescriptionToNull() noexcept;

    /**  For column capacity  */
    ///Get the value of the column capacity, returns the default value if the column is null
    const int32_t &getValueOfCapacity() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getCapacity() const noexcept;
    ///Set the value of the column capacity
    void setCapacity(const int32_t &pCapacity) noexcept;
    void setCapacityToNull() noexcept;

    /**  For column admin_email  */
    ///Get the value of the column admin_email, returns the default value if the column is null
    const std::string &getValueOfAdminEmail() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAdminEmail() const noexcept;
    ///Set the value of the column admin_email
    void setAdminEmail(const std::string &pAdminEmail) noexcept;
    void setAdminEmail(std::string &&pAdminEmail) noexcept;
    void setAdminEmailToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 7;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Rooms>;
    friend drogon::orm::BaseBuilder<Rooms, true, true>;
    friend drogon::orm::BaseBuilder<Rooms, true, false>;
    friend drogon::orm::BaseBuilder<Rooms, false, true>;
    friend drogon::orm::BaseBuilder<Rooms, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Rooms>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> roomId_;
    std::shared_ptr<int32_t> areaId_;
    std::shared_ptr<std::string> displayName_;
    std::shared_ptr<std::string> sortKey_;
    std::shared_ptr<std::string> description_;
    std::shared_ptr<int32_t> capacity_;
    std::shared_ptr<std::string> adminEmail_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[7]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where room_id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where room_id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "room_id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "area_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "display_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "sort_key,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "description,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "capacity,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "admin_email,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace mrbs
} // namespace postgres
} // namespace drogon_model
