/**
 *
 *  Rooms.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Rooms.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::postgres::mrbs;

const std::string Rooms::Cols::_room_id = "\"room_id\"";
const std::string Rooms::Cols::_area_id = "\"area_id\"";
const std::string Rooms::Cols::_display_name = "\"display_name\"";
const std::string Rooms::Cols::_sort_key = "\"sort_key\"";
const std::string Rooms::Cols::_description = "\"description\"";
const std::string Rooms::Cols::_capacity = "\"capacity\"";
const std::string Rooms::Cols::_admin_email = "\"admin_email\"";
const std::string Rooms::primaryKeyName = "room_id";
const bool Rooms::hasPrimaryKey = true;
const std::string Rooms::tableName = "mrbs.\"rooms\"";

const std::vector<typename Rooms::MetaData> Rooms::metaData_={
{"room_id","int32_t","integer",4,1,1,1},
{"area_id","int32_t","integer",4,1,0,1},
{"display_name","std::string","text",0,0,0,1},
{"sort_key","std::string","text",0,0,0,1},
{"description","std::string","text",0,0,0,0},
{"capacity","int32_t","integer",4,0,0,0},
{"admin_email","std::string","text",0,0,0,0}
};
const std::string &Rooms::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Rooms::Rooms(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["room_id"].isNull())
        {
            roomId_=std::make_shared<int32_t>(r["room_id"].as<int32_t>());
        }
        if(!r["area_id"].isNull())
        {
            areaId_=std::make_shared<int32_t>(r["area_id"].as<int32_t>());
        }
        if(!r["display_name"].isNull())
        {
            displayName_=std::make_shared<std::string>(r["display_name"].as<std::string>());
        }
        if(!r["sort_key"].isNull())
        {
            sortKey_=std::make_shared<std::string>(r["sort_key"].as<std::string>());
        }
        if(!r["description"].isNull())
        {
            description_=std::make_shared<std::string>(r["description"].as<std::string>());
        }
        if(!r["capacity"].isNull())
        {
            capacity_=std::make_shared<int32_t>(r["capacity"].as<int32_t>());
        }
        if(!r["admin_email"].isNull())
        {
            adminEmail_=std::make_shared<std::string>(r["admin_email"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 7 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            roomId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            areaId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            displayName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            sortKey_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            description_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            capacity_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            adminEmail_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Rooms::Rooms(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            roomId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            areaId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            displayName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            sortKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            capacity_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            adminEmail_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
}

Rooms::Rooms(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("room_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["room_id"].isNull())
        {
            roomId_=std::make_shared<int32_t>((int32_t)pJson["room_id"].asInt64());
        }
    }
    if(pJson.isMember("area_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["area_id"].isNull())
        {
            areaId_=std::make_shared<int32_t>((int32_t)pJson["area_id"].asInt64());
        }
    }
    if(pJson.isMember("display_name"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["display_name"].isNull())
        {
            displayName_=std::make_shared<std::string>(pJson["display_name"].asString());
        }
    }
    if(pJson.isMember("sort_key"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["sort_key"].isNull())
        {
            sortKey_=std::make_shared<std::string>(pJson["sort_key"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("capacity"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["capacity"].isNull())
        {
            capacity_=std::make_shared<int32_t>((int32_t)pJson["capacity"].asInt64());
        }
    }
    if(pJson.isMember("admin_email"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["admin_email"].isNull())
        {
            adminEmail_=std::make_shared<std::string>(pJson["admin_email"].asString());
        }
    }
}

void Rooms::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            roomId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            areaId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            displayName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            sortKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            capacity_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            adminEmail_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
}

void Rooms::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("room_id"))
    {
        if(!pJson["room_id"].isNull())
        {
            roomId_=std::make_shared<int32_t>((int32_t)pJson["room_id"].asInt64());
        }
    }
    if(pJson.isMember("area_id"))
    {
        if(!pJson["area_id"].isNull())
        {
            areaId_=std::make_shared<int32_t>((int32_t)pJson["area_id"].asInt64());
        }
    }
    if(pJson.isMember("display_name"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["display_name"].isNull())
        {
            displayName_=std::make_shared<std::string>(pJson["display_name"].asString());
        }
    }
    if(pJson.isMember("sort_key"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["sort_key"].isNull())
        {
            sortKey_=std::make_shared<std::string>(pJson["sort_key"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("capacity"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["capacity"].isNull())
        {
            capacity_=std::make_shared<int32_t>((int32_t)pJson["capacity"].asInt64());
        }
    }
    if(pJson.isMember("admin_email"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["admin_email"].isNull())
        {
            adminEmail_=std::make_shared<std::string>(pJson["admin_email"].asString());
        }
    }
}

const int32_t &Rooms::getValueOfRoomId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(roomId_)
        return *roomId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Rooms::getRoomId() const noexcept
{
    return roomId_;
}
void Rooms::setRoomId(const int32_t &pRoomId) noexcept
{
    roomId_ = std::make_shared<int32_t>(pRoomId);
    dirtyFlag_[0] = true;
}
const typename Rooms::PrimaryKeyType & Rooms::getPrimaryKey() const
{
    assert(roomId_);
    return *roomId_;
}

const int32_t &Rooms::getValueOfAreaId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(areaId_)
        return *areaId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Rooms::getAreaId() const noexcept
{
    return areaId_;
}
void Rooms::setAreaId(const int32_t &pAreaId) noexcept
{
    areaId_ = std::make_shared<int32_t>(pAreaId);
    dirtyFlag_[1] = true;
}

const std::string &Rooms::getValueOfDisplayName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(displayName_)
        return *displayName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Rooms::getDisplayName() const noexcept
{
    return displayName_;
}
void Rooms::setDisplayName(const std::string &pDisplayName) noexcept
{
    displayName_ = std::make_shared<std::string>(pDisplayName);
    dirtyFlag_[2] = true;
}
void Rooms::setDisplayName(std::string &&pDisplayName) noexcept
{
    displayName_ = std::make_shared<std::string>(std::move(pDisplayName));
    dirtyFlag_[2] = true;
}

const std::string &Rooms::getValueOfSortKey() const noexcept
{
    static const std::string defaultValue = std::string();
    if(sortKey_)
        return *sortKey_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Rooms::getSortKey() const noexcept
{
    return sortKey_;
}
void Rooms::setSortKey(const std::string &pSortKey) noexcept
{
    sortKey_ = std::make_shared<std::string>(pSortKey);
    dirtyFlag_[3] = true;
}
void Rooms::setSortKey(std::string &&pSortKey) noexcept
{
    sortKey_ = std::make_shared<std::string>(std::move(pSortKey));
    dirtyFlag_[3] = true;
}

const std::string &Rooms::getValueOfDescription() const noexcept
{
    static const std::string defaultValue = std::string();
    if(description_)
        return *description_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Rooms::getDescription() const noexcept
{
    return description_;
}
void Rooms::setDescription(const std::string &pDescription) noexcept
{
    description_ = std::make_shared<std::string>(pDescription);
    dirtyFlag_[4] = true;
}
void Rooms::setDescription(std::string &&pDescription) noexcept
{
    description_ = std::make_shared<std::string>(std::move(pDescription));
    dirtyFlag_[4] = true;
}
void Rooms::setDescriptionToNull() noexcept
{
    description_.reset();
    dirtyFlag_[4] = true;
}

const int32_t &Rooms::getValueOfCapacity() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(capacity_)
        return *capacity_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Rooms::getCapacity() const noexcept
{
    return capacity_;
}
void Rooms::setCapacity(const int32_t &pCapacity) noexcept
{
    capacity_ = std::make_shared<int32_t>(pCapacity);
    dirtyFlag_[5] = true;
}
void Rooms::setCapacityToNull() noexcept
{
    capacity_.reset();
    dirtyFlag_[5] = true;
}

const std::string &Rooms::getValueOfAdminEmail() const noexcept
{
    static const std::string defaultValue = std::string();
    if(adminEmail_)
        return *adminEmail_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Rooms::getAdminEmail() const noexcept
{
    return adminEmail_;
}
void Rooms::setAdminEmail(const std::string &pAdminEmail) noexcept
{
    adminEmail_ = std::make_shared<std::string>(pAdminEmail);
    dirtyFlag_[6] = true;
}
void Rooms::setAdminEmail(std::string &&pAdminEmail) noexcept
{
    adminEmail_ = std::make_shared<std::string>(std::move(pAdminEmail));
    dirtyFlag_[6] = true;
}
void Rooms::setAdminEmailToNull() noexcept
{
    adminEmail_.reset();
    dirtyFlag_[6] = true;
}

void Rooms::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Rooms::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "display_name",
        "sort_key",
        "description",
        "capacity",
        "admin_email"
    };
    return inCols;
}

void Rooms::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[2])
    {
        if(getDisplayName())
        {
            binder << getValueOfDisplayName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSortKey())
        {
            binder << getValueOfSortKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCapacity())
        {
            binder << getValueOfCapacity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getAdminEmail())
        {
            binder << getValueOfAdminEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Rooms::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    return ret;
}

void Rooms::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[2])
    {
        if(getDisplayName())
        {
            binder << getValueOfDisplayName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSortKey())
        {
            binder << getValueOfSortKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCapacity())
        {
            binder << getValueOfCapacity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getAdminEmail())
        {
            binder << getValueOfAdminEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Rooms::toJson() const
{
    Json::Value ret;
    if(getRoomId())
    {
        ret["room_id"]=getValueOfRoomId();
    }
    else
    {
        ret["room_id"]=Json::Value();
    }
    if(getAreaId())
    {
        ret["area_id"]=getValueOfAreaId();
    }
    else
    {
        ret["area_id"]=Json::Value();
    }
    if(getDisplayName())
    {
        ret["display_name"]=getValueOfDisplayName();
    }
    else
    {
        ret["display_name"]=Json::Value();
    }
    if(getSortKey())
    {
        ret["sort_key"]=getValueOfSortKey();
    }
    else
    {
        ret["sort_key"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getCapacity())
    {
        ret["capacity"]=getValueOfCapacity();
    }
    else
    {
        ret["capacity"]=Json::Value();
    }
    if(getAdminEmail())
    {
        ret["admin_email"]=getValueOfAdminEmail();
    }
    else
    {
        ret["admin_email"]=Json::Value();
    }
    return ret;
}

Json::Value Rooms::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 7)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getRoomId())
            {
                ret[pMasqueradingVector[0]]=getValueOfRoomId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getAreaId())
            {
                ret[pMasqueradingVector[1]]=getValueOfAreaId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDisplayName())
            {
                ret[pMasqueradingVector[2]]=getValueOfDisplayName();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getSortKey())
            {
                ret[pMasqueradingVector[3]]=getValueOfSortKey();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getDescription())
            {
                ret[pMasqueradingVector[4]]=getValueOfDescription();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getCapacity())
            {
                ret[pMasqueradingVector[5]]=getValueOfCapacity();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getAdminEmail())
            {
                ret[pMasqueradingVector[6]]=getValueOfAdminEmail();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getRoomId())
    {
        ret["room_id"]=getValueOfRoomId();
    }
    else
    {
        ret["room_id"]=Json::Value();
    }
    if(getAreaId())
    {
        ret["area_id"]=getValueOfAreaId();
    }
    else
    {
        ret["area_id"]=Json::Value();
    }
    if(getDisplayName())
    {
        ret["display_name"]=getValueOfDisplayName();
    }
    else
    {
        ret["display_name"]=Json::Value();
    }
    if(getSortKey())
    {
        ret["sort_key"]=getValueOfSortKey();
    }
    else
    {
        ret["sort_key"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getCapacity())
    {
        ret["capacity"]=getValueOfCapacity();
    }
    else
    {
        ret["capacity"]=Json::Value();
    }
    if(getAdminEmail())
    {
        ret["admin_email"]=getValueOfAdminEmail();
    }
    else
    {
        ret["admin_email"]=Json::Value();
    }
    return ret;
}

bool Rooms::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("room_id"))
    {
        if(!validJsonOfField(0, "room_id", pJson["room_id"], err, true))
            return false;
    }
    if(pJson.isMember("area_id"))
    {
        if(!validJsonOfField(1, "area_id", pJson["area_id"], err, true))
            return false;
    }
    if(pJson.isMember("display_name"))
    {
        if(!validJsonOfField(2, "display_name", pJson["display_name"], err, true))
            return false;
    }
    else
    {
        err="The display_name column cannot be null";
        return false;
    }
    if(pJson.isMember("sort_key"))
    {
        if(!validJsonOfField(3, "sort_key", pJson["sort_key"], err, true))
            return false;
    }
    else
    {
        err="The sort_key column cannot be null";
        return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(4, "description", pJson["description"], err, true))
            return false;
    }
    if(pJson.isMember("capacity"))
    {
        if(!validJsonOfField(5, "capacity", pJson["capacity"], err, true))
            return false;
    }
    if(pJson.isMember("admin_email"))
    {
        if(!validJsonOfField(6, "admin_email", pJson["admin_email"], err, true))
            return false;
    }
    return true;
}
bool Rooms::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Rooms::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("room_id"))
    {
        if(!validJsonOfField(0, "room_id", pJson["room_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("area_id"))
    {
        if(!validJsonOfField(1, "area_id", pJson["area_id"], err, false))
            return false;
    }
    if(pJson.isMember("display_name"))
    {
        if(!validJsonOfField(2, "display_name", pJson["display_name"], err, false))
            return false;
    }
    if(pJson.isMember("sort_key"))
    {
        if(!validJsonOfField(3, "sort_key", pJson["sort_key"], err, false))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(4, "description", pJson["description"], err, false))
            return false;
    }
    if(pJson.isMember("capacity"))
    {
        if(!validJsonOfField(5, "capacity", pJson["capacity"], err, false))
            return false;
    }
    if(pJson.isMember("admin_email"))
    {
        if(!validJsonOfField(6, "admin_email", pJson["admin_email"], err, false))
            return false;
    }
    return true;
}
bool Rooms::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Rooms::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            else
            {
                err="The automatic primary key cannot be update";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
