-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.mrbs_area (
  id integer NOT NULL DEFAULT nextval('mrbs_area_id_seq'::regclass),
  disabled smallint NOT NULL DEFAULT 0,
  area_name character varying UNIQUE,
  sort_key character varying NOT NULL DEFAULT ''::character varying,
  timezone character varying,
  area_admin_email text,
  resolution integer,
  default_duration integer,
  default_duration_all_day smallint NOT NULL DEFAULT 0,
  morningstarts integer,
  morningstarts_minutes integer,
  eveningends integer,
  eveningends_minutes integer,
  private_enabled smallint,
  private_default smallint,
  private_mandatory smallint,
  private_override character varying,
  min_create_ahead_enabled smallint,
  min_create_ahead_secs integer,
  max_create_ahead_enabled smallint,
  max_create_ahead_secs integer,
  min_delete_ahead_enabled smallint,
  min_delete_ahead_secs integer,
  max_delete_ahead_enabled smallint,
  max_delete_ahead_secs integer,
  max_per_day_enabled smallint NOT NULL DEFAULT 0,
  max_per_day integer NOT NULL DEFAULT 0,
  max_per_week_enabled smallint NOT NULL DEFAULT 0,
  max_per_week integer NOT NULL DEFAULT 0,
  max_per_month_enabled smallint NOT NULL DEFAULT 0,
  max_per_month integer NOT NULL DEFAULT 0,
  max_per_year_enabled smallint NOT NULL DEFAULT 0,
  max_per_year integer NOT NULL DEFAULT 0,
  max_per_future_enabled smallint NOT NULL DEFAULT 0,
  max_per_future integer NOT NULL DEFAULT 0,
  max_secs_per_day_enabled smallint NOT NULL DEFAULT 0,
  max_secs_per_day integer NOT NULL DEFAULT 0,
  max_secs_per_week_enabled smallint NOT NULL DEFAULT 0,
  max_secs_per_week integer NOT NULL DEFAULT 0,
  max_secs_per_month_enabled smallint NOT NULL DEFAULT 0,
  max_secs_per_month integer NOT NULL DEFAULT 0,
  max_secs_per_year_enabled smallint NOT NULL DEFAULT 0,
  max_secs_per_year integer NOT NULL DEFAULT 0,
  max_secs_per_future_enabled smallint NOT NULL DEFAULT 0,
  max_secs_per_future integer NOT NULL DEFAULT 0,
  max_duration_enabled smallint NOT NULL DEFAULT 0,
  max_duration_secs integer NOT NULL DEFAULT 0,
  max_duration_periods integer NOT NULL DEFAULT 0,
  custom_html text,
  approval_enabled smallint,
  reminders_enabled smallint,
  enable_periods smallint,
  periods text,
  confirmation_enabled smallint,
  confirmed_default smallint,
  times_along_top smallint NOT NULL DEFAULT 0,
  default_type character NOT NULL DEFAULT 'E'::bpchar,
  CONSTRAINT mrbs_area_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mrbs_entry (
  id integer NOT NULL DEFAULT nextval('mrbs_entry_id_seq'::regclass),
  start_time integer NOT NULL DEFAULT 0,
  end_time integer NOT NULL DEFAULT 0,
  entry_type integer NOT NULL DEFAULT 0,
  repeat_id integer,
  room_id integer NOT NULL DEFAULT 1,
  timestamp timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  create_by character varying NOT NULL DEFAULT ''::character varying,
  modified_by character varying NOT NULL DEFAULT ''::character varying,
  name character varying NOT NULL DEFAULT ''::character varying,
  type character NOT NULL DEFAULT 'E'::bpchar,
  description text,
  status smallint NOT NULL DEFAULT 0,
  reminded integer,
  info_time integer,
  info_user character varying,
  info_text text,
  ical_uid character varying NOT NULL DEFAULT ''::character varying,
  ical_sequence smallint NOT NULL DEFAULT 0,
  ical_recur_id character varying DEFAULT NULL::character varying,
  allow_registration smallint NOT NULL DEFAULT 0,
  registrant_limit integer NOT NULL DEFAULT 0,
  registrant_limit_enabled smallint NOT NULL DEFAULT 1,
  registration_opens integer NOT NULL DEFAULT 1209600,
  registration_opens_enabled smallint NOT NULL DEFAULT 0,
  registration_closes integer NOT NULL DEFAULT 0,
  registration_closes_enabled smallint NOT NULL DEFAULT 0,
  CONSTRAINT mrbs_entry_pkey PRIMARY KEY (id),
  CONSTRAINT mrbs_entry_repeat_id_fkey FOREIGN KEY (repeat_id) REFERENCES public.mrbs_repeat(id),
  CONSTRAINT mrbs_entry_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.mrbs_room(id)
);
CREATE TABLE public.mrbs_participants (
  id integer NOT NULL DEFAULT nextval('mrbs_participants_id_seq'::regclass),
  entry_id integer NOT NULL,
  username character varying,
  create_by character varying,
  registered integer,
  CONSTRAINT mrbs_participants_pkey PRIMARY KEY (id),
  CONSTRAINT mrbs_participants_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES public.mrbs_entry(id)
);
CREATE TABLE public.mrbs_repeat (
  id integer NOT NULL DEFAULT nextval('mrbs_repeat_id_seq'::regclass),
  start_time integer NOT NULL DEFAULT 0,
  end_time integer NOT NULL DEFAULT 0,
  rep_type integer NOT NULL DEFAULT 0,
  end_date integer NOT NULL DEFAULT 0,
  rep_opt character varying NOT NULL DEFAULT ''::character varying,
  room_id integer NOT NULL DEFAULT 1,
  timestamp timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  create_by character varying NOT NULL DEFAULT ''::character varying,
  modified_by character varying NOT NULL DEFAULT ''::character varying,
  name character varying NOT NULL DEFAULT ''::character varying,
  type character NOT NULL DEFAULT 'E'::bpchar,
  description text,
  rep_interval smallint NOT NULL DEFAULT 1,
  month_absolute smallint,
  month_relative character varying DEFAULT NULL::character varying,
  status smallint NOT NULL DEFAULT 0,
  reminded integer,
  info_time integer,
  info_user character varying,
  info_text text,
  ical_uid character varying NOT NULL DEFAULT ''::character varying,
  ical_sequence smallint NOT NULL DEFAULT 0,
  CONSTRAINT mrbs_repeat_pkey PRIMARY KEY (id),
  CONSTRAINT mrbs_repeat_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.mrbs_room(id)
);
CREATE TABLE public.mrbs_room (
  id integer NOT NULL DEFAULT nextval('mrbs_room_id_seq'::regclass),
  disabled smallint NOT NULL DEFAULT 0,
  area_id integer NOT NULL DEFAULT 0,
  room_name character varying NOT NULL,
  sort_key character varying NOT NULL,
  description character varying,
  capacity integer NOT NULL DEFAULT 0,
  room_admin_email text,
  invalid_types character varying DEFAULT NULL::character varying,
  custom_html text,
  CONSTRAINT mrbs_room_pkey PRIMARY KEY (id),
  CONSTRAINT mrbs_room_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.mrbs_area(id)
);
CREATE TABLE public.mrbs_sessions (
  id character varying NOT NULL,
  access integer,
  data text,
  CONSTRAINT mrbs_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mrbs_users (
  id integer NOT NULL DEFAULT nextval('mrbs_users_id_seq'::regclass),
  level smallint NOT NULL DEFAULT 0,
  name character varying UNIQUE,
  display_name character varying,
  password_hash character varying,
  email character varying,
  timestamp timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  last_login integer NOT NULL DEFAULT 0,
  reset_key_hash character varying,
  reset_key_expiry integer NOT NULL DEFAULT 0,
  CONSTRAINT mrbs_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mrbs_variables (
  id integer NOT NULL DEFAULT nextval('mrbs_variables_id_seq'::regclass),
  variable_name character varying UNIQUE,
  variable_content text,
  CONSTRAINT mrbs_variables_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mrbs_zoneinfo (
  id integer NOT NULL DEFAULT nextval('mrbs_zoneinfo_id_seq'::regclass),
  timezone character varying NOT NULL DEFAULT ''::character varying,
  outlook_compatible smallint NOT NULL DEFAULT 0,
  vtimezone text,
  last_updated integer NOT NULL DEFAULT 0,
  CONSTRAINT mrbs_zoneinfo_pkey PRIMARY KEY (id)
);
