import { getOpeningTime, type Booking } from "@/models/booking";
import { Rooms, type Room } from "@/models/rooms";
import { getBookings } from "@/services/booking-service";
import dayjs, { Dayjs } from "dayjs";
import { useEffect, useState } from "react";
import React from "react"
import isBetween from "dayjs/plugin/isBetween";
import { Dialog } from "./ui/dialog";
import NewBookingForm from "./new-booking-form";
import { useNavigate } from "react-router-dom";
import { useUser } from "@/context/user-context";
dayjs.extend(isBetween);

/**
 *  Show bookings for all rooms on a given day.
 *
 */
export default function DailyBookings({ currDate }: { currDate: Dayjs }) {
    const NUM_ROOMS = Rooms.length;
    const startTime: Dayjs = getOpeningTime(currDate);
    const TIME_SLOTS: Array<Dayjs> = Array.from({ length: 36 }, (_, i) => { return startTime.add(i * 30, "minute") })
    const [bookings, setBookings] = useState<Booking[]>([]);

    const [now, setNow] = useState(dayjs()); // Track current time (for the red line)
    const [isDialogOpen, setIsDialogOpen] = useState(false);
    const [selectedSlot, setSelectedSlot] = useState<{ room: Room; time: Dayjs; } | null>(null);
    const navigate = useNavigate();
    const user = useUser();
    const [refresh, setRefresh] = useState(1);

    // Load bookings data
    useEffect(() => {
        async function loadData() {
            const bookings = await getBookings(currDate.format("YYYY-MM-DD"));
            setBookings(bookings);
        }

        loadData()
    }, [currDate, refresh]);

    // Refresh current time every minute
    useEffect(() => {
        const timer = setInterval(() => setNow(dayjs()), 60000)
        return () => clearInterval(timer)
    }, []);

    // Generated by Gemini
    const getCurrentTimePosition = () => {
        // Calculate difference in minutes from grid start
        const diffMinutes = now.diff(startTime, 'minute');

        // If time is before start or after end, don't show
        if (diffMinutes < 0 || diffMinutes > TIME_SLOTS.length * 30) return null;

        // Calculate row. 
        // 30 mins = 1 row. 
        // We add +2 because Row 1 is Header, Row 2 is the first time slot.
        // We use floating point numbers here to place the line *inside* the row accurately.
        const rowStart = (diffMinutes / 30) + 2;

        return {
            gridColumn: `1 / -1`, // Span across all columns
            gridRowStart: rowStart,
            // We use a tiny span or just position it absolutely within the grid context
            marginTop: '-1px' // Adjustment to center on the exact minute
        };
    };

    const timePos = getCurrentTimePosition();

    // Get Column Index for a Room (1-based index)
    // Time column is #1, so Room 1 is #2, Room 2 is #3...
    const getColIndex = (roomId: string) => {
        const index = Rooms.findIndex(r => r.room_id === roomId);
        return index + 2; // +1 for 0-index, +1 for Time column
    };

    // Get Row Start/Span for a Booking
    const getRowPosition = (booking: Booking) => {
        const start = dayjs(booking.start_time);
        const end = dayjs(booking.end_time);

        // Calculate difference in minutes from grid start (8:00 AM)
        const diffMinutes = start.diff(startTime, 'minute') + 1;

        // Each row is 30 mins. +2 because Row 1 is Header, Row 2 is 8:00 AM
        const startRow = Math.floor(diffMinutes / 30) + 2;

        const durationMinutes = end.diff(start, 'minute');
        const span = Math.ceil(durationMinutes / 30);

        return {
            gridColumn: getColIndex(booking.room_id),
            gridRowStart: startRow,
            gridRowEnd: `span ${span}`
        };
    };

    // Helper: Check if a specific time slot in a room is occupied
    const isSlotOccupied = (roomId: string, slotTime: Dayjs) => {
        return bookings.some(booking => {
            if (booking.room_id !== roomId) return false;

            const bookingStart = dayjs(booking.start_time);
            const bookingEnd = dayjs(booking.end_time);

            // Check if the slot time falls within the booking window
            // [Start, End) - Inclusive of start, exclusive of end
            return (slotTime.isSame(bookingStart) || slotTime.isAfter(bookingStart)) && slotTime.isBefore(bookingEnd);
        });
    };

    const handleSlotClick = (room: Room, time: Dayjs) => {
        // Double check to prevent hacking via console
        if (isSlotOccupied(room.room_id, time)) return;

        // If user is not logged in, redirect to login page.
        if (user == null)
            navigate("/login")

        setSelectedSlot({ room, time });
        setIsDialogOpen(true);
    };

    return (
        <div className="w-full h-full overflow-auto border rounded-md bd-card isolate">
            <div
                className="min-w-max grid bg-background"
                style={{
                    // Define Tracks explicitly
                    gridTemplateColumns: `76px repeat(${NUM_ROOMS}, minmax(136px, 1fr))`,
                    // Header is auto height, Time slots are fixed 32px
                    gridTemplateRows: `60px repeat(${TIME_SLOTS.length}, 30px)`
                }}
            >
                {/* --- HEADER ROW (Row 1) --- */}
                <div className="sticky top-0 left-0 z-50 p-4 bg-sky-100 dark:bg-sky-900 border-b border-r font-medium text-sm text-sky-800 dark:text-sky-100 uppercase tracking-wider flex items-center justify-center col-start-1 row-start-1">
                    Time
                </div>
                {Rooms.map((room, i) => (
                    <div
                        key={`header-${room.room_id}`}
                        className="sticky top-0 z-40 p-2 bg-sky-100 dark:bg-sky-900 text-center border-b border-r last:border-r-0 flex flex-col justify-center items-center"
                        style={{ gridColumn: i + 2, gridRow: 1 }}
                    >
                        <div className="font-semibold text-sm text-sky-900 dark:text-sky-100">{room.display_name}</div>
                        <div className="text-xs text-sky-700 dark:text-sky-300">({room.capacity} pax)</div>
                    </div>
                ))}

                {/* --- BACKGROUND GRID (Rows 2..N) --- */}
                {TIME_SLOTS.map((slot, i) => {
                    const currentRow = i + 2;
                    return (
                        <React.Fragment key={`row-${i}`}>
                            {/* Time Label (Col 1) */}
                            <div
                                className="sticky left-0 z-30 bg-background border-b border-r text-xs text-muted-foreground flex items-center justify-center"
                                style={{ gridColumn: 1, gridRow: currentRow }}
                            >
                                {slot.format("hh:mm A")}
                            </div>

                            {/* Empty Room Cells (Cols 2..N) - Just for visual grid lines */}
                            {Rooms.map((room, roomIdx) => {
                                const isOccupied = isSlotOccupied(room.room_id, slot)

                                return (
                                    <div
                                        key={`grid-${room.room_id}-${i}`}
                                        className={`border-b border-r even:bg-muted/35 last:border-r-0 hover:bg-muted/30 transition-colors ${isOccupied
                                            ? "bg-muted/50 cursor-not-allowed hatch-pattern" // Disabled style
                                            : "cursor-pointer hover:bg-sky-100/50" // Active style
                                            }`}
                                        style={{ gridColumn: roomIdx + 2, gridRow: currentRow }}
                                        onClick={() => !isOccupied && handleSlotClick(room, slot)}
                                    />
                                )
                            }
                            )}
                        </React.Fragment>
                    );
                })}

                {/* --- BOOKINGS OVERLAY --- */}
                {bookings.map((booking) => {
                    const style = getRowPosition(booking);
                    // Filter out bookings that are completely out of bounds (optional safety)
                    if (style.gridRowStart < 2) return null;

                    // Manual truncation coz for some reason I couldn't get the tailwind classes to cooperate.
                    const MAX_TEXT_LENGTH = 20;
                    if (booking.title.length > MAX_TEXT_LENGTH) {
                        booking.title = booking.title.slice(0, MAX_TEXT_LENGTH);
                        booking.title = `${booking.title}...`
                    }

                    if (booking.booked_by.length > MAX_TEXT_LENGTH) {
                        booking.booked_by = `${booking.booked_by.slice(0, MAX_TEXT_LENGTH)}...`
                    }

                    return (
                        <div
                            key={booking.booking_id}
                            className="group truncate z-10 m-1 rounded bg-sky-100 border-l-4 border-sky-500 dark:bg-sky-900/80 dark:border-sky-400 p-2 text-xs shadow-sm hover:brightness-95 cursor-pointer overflow-hidden flex flex-col justify-center "
                            style={style}
                            title={`${booking.title} (${dayjs(booking.start_time).format("HH:mm")} - ${dayjs(booking.end_time).format("HH:mm")})`
                            }
                        >
                            <div className="font-semibold text-sky-900 dark:text-sky-100 truncate">
                                {booking.title}
                            </div>
                            <div className="text-sky-800 dark:text-sky-200 text-[11px] ">
                                {booking.booked_by}
                            </div>
                            <div className="text-sky-700 dark:text-sky-300 truncate text-[10px] hidden group-hover:block" >
                                {dayjs(booking.start_time).format("hh:mm")} - {dayjs(booking.end_time).format("hh:mm A")}
                            </div>
                        </div>
                    );
                })}

                {/* --- CURRENT TIME INDICATOR --- */}
                {timePos && (
                    <div
                        className="z-50 border-t-2 border-red-500 w-full pointer-events-none flex items-center"
                        style={{
                            gridColumn: '1 / -1', // Span entire width
                            gridRowStart: Math.floor(timePos.gridRowStart), // Snap to the row
                            marginTop: `${(timePos.gridRowStart % 1) * 32}px`, // Push down by % of row height (32px)
                        }}
                    >
                        {/* Current time indicator */}
                        <div className="bg-red-500 text-white text-[10px] px-1 rounded-r -ml-px">
                            {now.format("hh:mm A")}
                        </div>
                    </div>
                )}

            </div>

            <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
                {
                    selectedSlot &&
                    <NewBookingForm room={selectedSlot.room} time={selectedSlot.time} onSuccess={() => { setIsDialogOpen(false); setRefresh((r) => r + 1) }} />
                }
            </Dialog>
        </div >
    );
}



